export const moods = [
    { "id": 1, "name": "Heureux 😄" },
    { "id": 2, "name": "Triste 😢" },
    { "id": 3, "name": "Énervé 😡" },
    { "id": 4, "name": "Fatigué 😴" },
    { "id": 5, "name": "Excité 🤩" },
    { "id": 6, "name": "Inquiet 😰" },
    { "id": 7, "name": "Calme 😌" },
    { "id": 8, "name": "Stimulé ⚡" },
    { "id": 9, "name": "Étonné 😲" },
    { "id": 10, "name": "Motivé 💪" },
    { "id": 11, "name": "Déçu 😞" },
    { "id": 12, "name": "Reconnaissant 🙏" },
    { "id": 13, "name": "En paix 🕊️" },
    { "id": 14, "name": "Rêveur 🌙" },
    { "id": 15, "name": "Débordé 😵" },
    { "id": 16, "name": "Curieux 🤔" },
    { "id": 17, "name": "Confiant 😎" },
    { "id": 18, "name": "Pessimiste 😕" },
    { "id": 19, "name": "Optimiste 🌞" },
    { "id": 20, "name": "Anxieux 😟" },
    { "id": 21, "name": "Énergique 🌟" },
    { "id": 22, "name": "Épuisé 😫" },
    { "id": 23, "name": "Satisfait 😊" },
    { "id": 24, "name": "Perplexe 😕" },
    { "id": 25, "name": "Aimant ❤️" },
    { "id": 26, "name": "Joyeux 🤗" },
    { "id": 27, "name": "Inspiré ✨" },
    { "id": 28, "name": "Perdu 🌫️" },
    { "id": 29, "name": "Solitaire 😞" },
    { "id": 30, "name": "Déterminé 🏃‍♂️" },
    { "id": 31, "name": "Pensif 💭" },
    { "id": 32, "name": "Enthousiaste 🌈" },
    { "id": 33, "name": "Apaisé 🍃" },
    { "id": 34, "name": "Nostalgique 🕰️" },
    { "id": 35, "name": "Fier 🦁" },
    { "id": 36, "name": "Surpris 😮" },
    { "id": 37, "name": "Blessé 💔" },
    { "id": 38, "name": "Patienteux ⏳" },
    { "id": 39, "name": "Créatif 🎨" },
    { "id": 40, "name": "Honteux 😳" },
    { "id": 41, "name": "Reconforté 🤗" },
    { "id": 42, "name": "Méfiant 😒" },
    { "id": 43, "name": "Sur de soi 💪" },
    { "id": 44, "name": "Amusé 😂" },
    { "id": 45, "name": "Incompris 😔" },
    { "id": 46, "name": "Aventurier 🧭" },
    { "id": 47, "name": "Rassuré 💆" },
    { "id": 48, "name": "Jaloux 😒" },
    { "id": 49, "name": "Revanchard 🔥" },
    { "id": 50, "name": "Émerveillé 🌟" },

    { "id": 51, "name": "Ambitieux 🚀" },
    { "id": 52, "name": "Réfléchi 🧠" },
    { "id": 53, "name": "Content 😌" },
    { "id": 54, "name": "Serein 🧘" },
    { "id": 55, "name": "Décontracté 😎" },
    { "id": 56, "name": "Euphorique 🎉" },
    { "id": 57, "name": "Contrarié 🙁" },
    { "id": 58, "name": "Blessé 😢" },
    { "id": 59, "name": "Énervé 😤" },
    { "id": 60, "name": "Comblé 💖" },
    { "id": 61, "name": "Dégoûté 😣" },
    { "id": 62, "name": "Nostalgie 📸" },
    { "id": 63, "name": "Reconnaissant 🥰" },
    { "id": 64, "name": "Enthousiaste 😃" },
    { "id": 65, "name": "Mystérieux 🌌" },
    { "id": 66, "name": "Émotif 😢" },
    { "id": 67, "name": "Affamé 🍔" },
    { "id": 68, "name": "Sur la défensive 🛡️" },
    { "id": 69, "name": "Timide 😳" },
    { "id": 70, "name": "Soulagé 😌" },
    { "id": 71, "name": "Dynamique 💥" },
    { "id": 72, "name": "Aimant 💞" },
    { "id": 73, "name": "Pensif 🤔" },
    { "id": 74, "name": "Mélancolique 🍂" },
    { "id": 75, "name": "Passionné 🔥" },
    { "id": 76, "name": "Stressé 😩" },
    { "id": 77, "name": "Exaspéré 😣" },
    { "id": 78, "name": "Insatisfait 😕" },
    { "id": 79, "name": "Solitaire 🌃" },
    { "id": 80, "name": "Compréhensif 🤗" },
    { "id": 81, "name": "Enragé 💢" },
    { "id": 82, "name": "Révolté 🗣️" },
    { "id": 83, "name": "Sur un petit nuage ☁️" },
    { "id": 84, "name": "Vivant 💫" },
    { "id": 85, "name": "Indécis 😬" },
    { "id": 86, "name": "Lassé 😒" },
    { "id": 87, "name": "Responsable 🧑‍💼" },
    { "id": 88, "name": "Rassurant 💙" },
    { "id": 89, "name": "Frustré 😤" },
    { "id": 90, "name": "Inquiet 😟" },
    { "id": 91, "name": "Accueillant 👐" },
    { "id": 92, "name": "Attentif 👂" },
    { "id": 93, "name": "Gêné 😅" },
    { "id": 94, "name": "Fougueux 💥" },
    { "id": 95, "name": "Dévoué 🤲" },
    { "id": 96, "name": "Insouciant 🎈" },
    { "id": 97, "name": "Prudent 🦺" },
    { "id": 98, "name": "Festif 🥳" },
    { "id": 99, "name": "Incomplet 🧩" },
    { "id": 100, "name": "Persévérant 💪" }



]